version: '3'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server

        depends_on:
            - postgres
            
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev 
            context: ./client
    
    worker:
        build:
            dockerfile: Dockerfile.dev  
            context: ./worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        depends_on:
            - api
            - client
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports:
            - '3050:80'
